services:
  - type: web
    name: ama0507-tangolevel
    env: python
    region: Oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --port $PORT --host 0.0.0.0 main:app"
    envVars:
      - key: PYTHON_VERSION 
        value: 3.8.2
